### ISSUE TITLE
Where can `bigtilemap.py`, needed by `pmx.py` and referenced in the `README.md`, be found?

### ISSUE THREAD

**Issue by dreirund** [padorange/pmx-bigmap#3]
The [`README.md`](https://github.com/padorange/pmx-bigmap/blob/master/README.md?plain=1#L1-L4) says  
> This project is composed of 2 sub-projects :
> 
> * pmx.py, a GUI interface to explore maps and made fixed map ready to print
> * bigtilemap.py, a CLI interface to do the same

But `bigtikemap.py` I cannot find in the repository.

And just running `python3 pmx.py` fails with missing `bigtilemap`:  
```
Traceback (most recent call last):
  File "/tmp/pmx-bigmap/pmx.py", line 89, in <module>
    import bigtilemap		# bigtilemap : handle downloading and assembling tiles
    ^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'bigtilemap'
```

Regards!

**Comment by padorange** [comment]
Sorry my mistake
I should have correct it now and all files are in the repo
Thanks for your vigilance

**Comment by dreirund** [comment]
Thanks, now it is solved.
